const GET_ALL_TYPES = "GET_ALL_TYPES";
const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const SET_FILTER = "SET_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const REMOVE_ALL_FILTERS = "REMOVE_ALL_FILTERS";

export {
    GET_ALL_CATEGORIES,
    GET_ALL_TYPES,
    SET_FILTER,
    REMOVE_FILTER,
    REMOVE_ALL_FILTERS,
};
