const GET_ALL_EVENTS = "GET_ALL_EVENTS";
const SORT_EVENTS = "SORT_EVENTS";
const FILTERED_EVENTS = "FILTERED_EVENTS";
const DEFAULT_EVENT_LIST = "DEFAULT_EVENT_LIST";
const SET_FILTER = "SET_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const REMOVE_ALL_FILTERS = "REMOVE_ALL_FILTERS";

export {
    GET_ALL_EVENTS,
    SORT_EVENTS,
    FILTERED_EVENTS,
    SET_FILTER,
    REMOVE_FILTER,
    REMOVE_ALL_FILTERS,
    DEFAULT_EVENT_LIST,
};
