const GET_ALL_EVENTS = "GET_ALL_EVENTS";
const SORT_EVENTS = "SORT_EVENTS";
const FILTER_EVENTS = "FILTER_EVENTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";

export {
    GET_ALL_EVENTS,
    SORT_EVENTS,
    FILTER_EVENTS,
    CLEAR_FILTERS,
};
