const GET_ALL_EVENTS = "GET_ALL_EVENTS";
const GET_CREATED_USER_EVENTS = "GET_CREATED_USER_EVENTS";
const GET_MEMBERED_USER_EVENTS = "GET_MEMBERED_USER_EVENTS";
const SORT_EVENTS = "SORT_EVENTS";
const DEFAULT_EVENT_LIST = "DEFAULT_EVENT_LIST";
const SET_FILTER = "SET_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const REMOVE_ALL_FILTERS = "REMOVE_ALL_FILTERS";
const LOADING = "LOADING";
const LOADED= "LOADED";

export {
    GET_ALL_EVENTS,
    SORT_EVENTS,
    SET_FILTER,
    REMOVE_FILTER,
    REMOVE_ALL_FILTERS,
    DEFAULT_EVENT_LIST,
    GET_CREATED_USER_EVENTS,
    GET_MEMBERED_USER_EVENTS,
    LOADING,
    LOADED,
};
